[general]
use_gpu = true
nb_omp_threads = 0     # 0 = auto

[retrieval]
forward_model_type = "flat_line"
spectral_discretisation = "const_wavenumber"
spectral_resolution = 0.5
opacity_data_folder = "/media/data/opacity_data/helios-k/"
use_error_inflation = false
